### ISSUE TITLE
希望加入重试机制

### ISSUE THREAD

**Issue by ORO44** [NobeKanai/dvtag#1]
因为经常tag到一半, 就提示远程服务器已断开连接, 然后又得重新打一次, 数量一多就不知道打的进度了.

**Comment by NobeKanai** [comment]
可以使用 `nohup` 命令避免远程终端断开连接时程序中断， 例如
```bash
nohup dvtag -w2f /xx/xxx &
```
可以通过检查 `nohup.out` 文件观察程序输出

**Comment by ORO44** [comment]
> 可以使用 `nohup` 命令避免远程终端断开连接时程序中断， 例如
> 
> ```shell
> nohup dvtag -w2f /xx/xxx &
> ```
> 
> 可以通过检查 `nohup.out` 文件观察程序输出

我是windows环境, 不过解决了, 突然想起来我之前也遇到过, 我直接把requests请求再包上一层函数, 然后用while一直重试获取.
