### ISSUE TITLE
Storing the metadata to local files

### ISSUE THREAD

**Issue by zhyu** [NobeKanai/dvtag#11]
Can we add an optional argument to `dvtag` to store the metadata locally? I.e., storing the cover art as `folder.jpg` or `cover.jpg`, and storing other metadata in an [album.nfo](https://kodi.wiki/view/NFO_files/Albums) file.

It will enable Media servers like Emby, Jellyfin, Kodi, etc. to handle `wav` files (and other types of files) without needing to convert them to a different format.

**Comment by NobeKanai** [comment]
From available tags of [album.nfo](https://kodi.wiki/view/NFO_files/Albums), it seems like it doesn't cover individual tracks. This means media servers would have to guess the disc numbers, track numbers and titles for each track. 

The messy folder structure of these works also makes it difficult for the media server to understand which track belongs to which album. You will most likely need to organize them yourself, which... cost extra effort.

If the main reason for using separate metadata files is to handle `wav` files, I don't think it's worth the extra hassle. And `flac` is good for lossless audio.

**Comment by zhyu** [comment]
Not sure why it's not documented on the Kodi wiki, but `track` is a valid tag with `title` and `position` as sub-tags. An example can be found [here](https://forum.kodi.tv/showthread.php?tid=301392).

`wav` files will benefit from it for sure, but the usage is not limited to it. `album.nfo` supports metadata that ID3 tags not supporting, e.g., `rating`, which can be filled by the ratings on DLsite and correctly parsed by media servers. And it's the same for `votes`.

**Comment by NobeKanai** [comment]
Have you tried creating the `album.nfo` file yourself and seeing if it works properly? I personally only use Plex, but I tried using Emby and the `album.nfo` didn't seem to work as expected for me.

I still don't understand why you insist on using `wav` files. Also, rating and votes are values that change over time, and I don't think they should be in local metadata. Maybe a separate media server plugin that can frequently update these values from dlsite would be more suitable.

**Comment by zhyu** [comment]
> Have you tried creating the album.nfo file yourself and seeing if it works properly? I personally only use Plex, but I tried using Emby and the album.nfo didn't seem to work as expected for me.

You are correct. I just tried with Emby locally but it seems nfo files are not parsed as expected. I will close the issue then.

> I still don't understand why you insist on using wav files.

I just don't want to convert a large media collection only for the ID3 tags.

> Maybe a separate media server plugin that can frequently update these values from dlsite would be more suitable.

That's true. I will have a look. Thanks!
