### ISSUE TITLE
希望可以自定义ffmpeg转码的线程数

### ISSUE THREAD

**Issue by wubushanyan** [NobeKanai/dvtag#3]
希望可以自定义ffmpeg转码的线程数 ，在转码的时候CPU占用才20% 希望拉满

**Comment by NobeKanai** [comment]
wav -> flac 的转换通常性能瓶颈不在 CPU。 多核跑起来也没有太大的区别。 

转 mp3 多核是快了好多，过段时间可能会实现一下多进程版本,， 应该不会支持自定义。

如果你有需求的话可以手动用 ffmpeg 转码
