### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by wubushanyan** [NobeKanai/dvtag#4]
**报错**
> Traceback (most recent call last):
>   File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\Scripts\dvtag.exe\__main__.py", line 7, in <module>
>   File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\main.py", line 44, in main
>     start(path, args.w2f, args.w2m)
>   File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\main.py", line 25, in start
>     start(file, w2f, w2m)
>   File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\main.py", line 19, in start
>     tag(dirpath)
>   File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\dvtag\dvtag.py", line 76, in tag
>     dv = DoujinVoice(rjid)
>   File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\dvtag\doujinvoice.py", line 23, in __init__
>     self._init_metadata()
>   File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\dvtag\doujinvoice.py", line 62, in _init_metadata
>     json_data = rsp.json()[self.rjid]
> TypeError: list indices must be integers or slices, not str

**目录**

> ├── 1
> │   ├── RJ397140

**执行命令**

`dvtag -w2f ./`

在执行完wav转flac后，应该是打tag时弹出上面的报错

**Comment by NobeKanai** [comment]
[RJ397140](https://www.dlsite.com/maniax/work/=/product_id/RJ397140.html) 这部作品现在并不存在

**Comment by wubushanyan** [comment]
> [RJ397140](https://www.dlsite.com/maniax/work/=/product_id/RJ397140.html) 这部作品现在并不存在

啊这我感觉我好蠢啊 RJ391740 搞反了
