### ISSUE TITLE
希望转码能保留源文件

### ISSUE THREAD

**Issue by kafuuchino3** [NobeKanai/dvtag#7]
源文件的wav我想留着，希望可以选择是否保留源文件。
并且转码后的路径希望能够自定义，一般来说我本地会是 " \ASMR\RJXXXXXX\?????\wav\01_???.wav" 这种格式，我个人希望是转码后放到 " \ASMR\RJXXXXXX\?????\flac\01_???.flac" 或者 " \ASMR\RJXXXXXX\?????\wav\flac\01_???.flac" 这样的路径下。

**Comment by NobeKanai** [comment]
转码在 _dvtag_ 里只是顺带的对 ffmpeg 命令的简单封装。 如果你有其它的转码需求应该考虑直接调用 ffmpeg 命令来实现。 比如你这里的需求在 Linux 系统上只用一行命令就可以做到

```bash
find . -name "*.wav" | parallel 'mkdir -p {//}/flac && ffmpeg -i {} {//}/flac/{/.}.flac'
```

**Comment by kafuuchino3** [comment]
好的，谢谢解答
